language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/charts-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn clean
  deploy --settings deploy/settings.xml && exit 0; fi
env:
  global:
  - secure: Q5JrxTVaV3eWzGERrA5/3OWUJTfXPWbLrby2xFwP8yVp6kuqzNF1alHqzQle/N4fRHE31D3rCK2hr5jQ0Kyc54oAvNAzyxwi2wCq+g43QrB3KJlEb+0rbUiihVEYFBWt9fQ7dwaU2iE3CWrac1PkleyxbMAGT2flBttxOn7kZnjdDOE7DhHshG1ItGb3/Ttp/BoYLh8EyWH5FfjuDaN9i6kkEvXHCBgbUlQIwyO7O74zblTiTG6ycQnWeE7/GKAgs7JtCdvTUt+MVk7BldPgx0W929qCanKOtnq46vcw8sD9bdAdEqiFdi/cAM+vehb8QgDeZBEaAxnNNfI4wLV135m86H92c7n/5kULBmHsGrKyHfxyHYV2StNKxZZ/VqGn4nJjcjUtymaEVof1KNTmHnAb8VWrae0ddsNM0FnRVwOo1WLhprJSTQ+ypRWCYa5VrROSlGu5M4skvRQoXkVghVfofkLh6RHxyggjlC40fT5gw5+9HXV1qgB9hMn7lrj8PcfCxe0333VJ1219Ulttp5T2UBltxY2Ib5PheyNTaS+EKMTRZHLNk6LOuG1iKSuxa0uyAGbzRRxtdaZEJ31MLkRYcW8v7IFhJQas5lGumci5Bzzw8qI4K3N2BTyFSMgA1GSwbrESjD5nimMmo3xkE3fNRDxxiCCJ+/kchMBxWlw=
  - secure: alRSuJf8noxcE/qXT7SVtlzE5rrtR72dm9jgRfYtHfkZf6QM7CFHkTGCq2Zr/JfDcKI3hqV6B63m+9c4c69bv+6H9uI7WvNunrQNt3ms4x0wJgy7KsFuLemoVRax6sTjZSnFHH7LZT1gjP8RtnVvZwIPRHaNEaAV66hcE57TlPtiju0tdfE03x1cml8SkiliWIUYCtCLFAQ3vXm7PBHf46E/m6165ISNBAGpyJXL0MmQJKh3X3oKb1XjR2tCk08KQosSlvqudHn4X/fOZUxD9jHi8WO7MzXKGgv6sxhVX1M7kPI87tIuAw5ZAHiHn9dtkBrVJDDC30Y3BS5FVGZhNZb2/5m0Z/Jv63IqLFHrO2mVDER8Xg1U3e6/BAQPbfJP2G98FG+TRvwtDmOc753XINKkDiFwYjGcipxpk9hLkWbgO02raSP7x8tkCCV9/BIIVZBNRAobpCgdcDAnewUvy1/dFcFik6i32UkIZb1Dc6R4J//9LTcEl6U4keTD9E6u/g9pSJBy9cBR/Sp0vY+Dl63mj0+eSMaev9kykUpRGxudBLgtCG4sOJXZdwbITsbBJMZXdk+YvB1IkNk+E+LYPEuPRFPnAs7qqm4mp8OSrcrtXPhN5WnB3JqPwmzqmYXg82ezw+P1iVsg3tbjTKHTf5ZIkgfzOxupVcEWRU1Vnhs=
notifications:
  slack:
    secure: NK6aI39iR56wDGyQ1YZWOEktxAIMGSOwdud1R1FXKj3WwK2EGcIjPu4fOY5MTF80GvZwoAebRTnYn/qhGzmeTckGQwri0JuHd2NUU8zur5zzv3rj/Z1j0/juPURJOyBiUIU/4IINuc8ovBOw1LNWHPHQ81Mkz15Vm+2MMMMQcGZjeyWc6O5TT77tdpZH4OMRtr6BTTZ7gzR0JwvV3aFud3KbY+xntBhh7liuLnAeU8U68j5Ia7roAiIP/gpmpKRNp5yPvFBOVB0zug/68Ebveg0tjiz9h7g2FjLByAZ6kDnKy7yGFOMfxYfGyhnGhnfFA1cIatqli2SI9HnWsGwi8Kxp333G3TpwwIxn4Ad2nZIKJpWL+WCzzTpImEuRTWe+ylV8fj6sDQJB98/wGtyli6Y4QjRuANGwSBIDEBXgcPHHI69zWaG8IL/l0zkccjkrAVJfZL7g5oUSYQsZQCDYDdY33FcKnmCKWcOmKuPJqI+zljoHNAL+sXNwOx6l2WQ6ARRd0IP7BvQZmd816GhSHtQHPRxO7SJfqDYNvjlAzG2FIMf4Jx6vvJhXBcabjsN5BCXir4klzSqPaB/Uo8BPNhVV16IAUCG3OxBUTxIIEc1vTKV9C/9EMljKzJG4CrKejST8QIHVvQgAwXt8hUnlBmPsNs+4BN7OhNlLfIrgsPs=
    on_success: change
    on_failure: always
