language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
before_script:
- cd $HOME
- git clone --depth=10 -b v25 https://github.com/dhis2/d2-charts-api.git
- cd $HOME/d2-charts-api
- npm install
- npm run build
script:
- npm link d2-charts-api
- npm run build
after_success:
- cd $TRAVIS_BUILD_DIR
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/charts-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ;then mvn clean
  deploy --settings deploy/settings.xml && exit 0; fi
env:
  global:
  - secure: E7JbhdH+CdAvJJBc8yHIE66wy2++HjmDFR3CIZSaRWzXhJko7mBW3URwY5JQ2GD389nvSG5U6hL9gQ41qwMda0S8l3ibLPIUHJd60AEAK7IaWxjEYXl0aZLg4F5WAeTYkcJEVhYz2cd/8ch3qesb4xf1lzWFdEOqmlkCORTpTDjNfzz+YK/KglQkZ+j5k2Z2QYS9BevLK/42gzpcFkP52ssfuPl5/q8FlIF11kEwQ+qqVpU32zeoMkhCjxU0aNOXR5pYKoUGhpnY+g4CGqoN8u+p6xa1kg+l3XObBc92aRqu9V2v3ViW5uDmO9WFyqZPgXHKrrb7wO/C5tUxgEaH13zRMboqv8X51bakQ+6sbJlHxDMnFLejHKhj4iUXLulhurByIR0+sDDr2seGtkWFKOPonQGKQL2RyKZ9zleW9tlH0bLvHXwyaUrwX0zeeEVNIhs+dAa/xjDj7NK8KnTwRGsYo5K0x9UcmFild+OkfbWvWIAl2takjpF/SPD/3m3oq9W9ocH9tlhGaMwpMoIDReqAbLmAllr8I+mq44lJmhMw572f4UtPuSw8uXb++Y5wBVxhlX0nYLmjuUNzTQmWmSB7k53n8Mr5vLdXVcbgEEbgjJQ2GLJTXzWhQdBCF+8B2V4wu68IK4owSTI+ehdbSeB1lpckj9Ugrxe7vPvHDIc=
  - secure: VP0QlgMzHFP3DAygwqDxoabzDukM9NRZ1myZUktQBol1W2oCPNlQ6NPXnJXoH5YSE81MKWYSfjX7MbPOAtvWVHT5X7b9mqZa/vjclh75lgTT10u/i3H3nF4kL27RMZp1CEFK9g/HBuWdsuyb8SKChkAf0fEC9dtDsIX6WSRDmA+Yxlge7ujDLspV09bm4CTPbpcRQ2BvfC/21ybcOyQaqsYpsxjn1U76JzAXqFYsP1OuqPQJSwGQZnTIhqSwK5I0f4XXg563qKePA8pLeWV46N6KzCrIp5E/PExlhbUbZcQKCbuLL8JSistNI1TUycNJT7WQOCdwwSEPWukj5kuoSokAm1IXVlvunhz4KzR+AWWZRPOZDVgkTMGwe0y2LvKys/jRjdJguJiD/GE7wik4gOvIKrX5Vjo8YwdFwLn5wgCE624jAYh87dEtKRant9H/VCVSG248EnFSSzcYhc2svfZ1428ZWhtR+4B5Ub50M2ZAFALV8JqZ0yXR8WFl4k4++ZUsCK+zTSfxiilGyipIOVxe9urMNrBCNzsIrn9OkTew5vuVaUHbsU+U3/CbeLDxPW6hGtZ7cXTEUw2XzJMxtYvK8szK9kqLI9bUQfTZmsEdmUs9iCI7sf+wn5AZESreH6gJ9evlXuKcZ1WydK1Ulj7FtEFRIZKxiWApmoxbTBU=
notifications:
  slack:
    secure: NK6aI39iR56wDGyQ1YZWOEktxAIMGSOwdud1R1FXKj3WwK2EGcIjPu4fOY5MTF80GvZwoAebRTnYn/qhGzmeTckGQwri0JuHd2NUU8zur5zzv3rj/Z1j0/juPURJOyBiUIU/4IINuc8ovBOw1LNWHPHQ81Mkz15Vm+2MMMMQcGZjeyWc6O5TT77tdpZH4OMRtr6BTTZ7gzR0JwvV3aFud3KbY+xntBhh7liuLnAeU8U68j5Ia7roAiIP/gpmpKRNp5yPvFBOVB0zug/68Ebveg0tjiz9h7g2FjLByAZ6kDnKy7yGFOMfxYfGyhnGhnfFA1cIatqli2SI9HnWsGwi8Kxp333G3TpwwIxn4Ad2nZIKJpWL+WCzzTpImEuRTWe+ylV8fj6sDQJB98/wGtyli6Y4QjRuANGwSBIDEBXgcPHHI69zWaG8IL/l0zkccjkrAVJfZL7g5oUSYQsZQCDYDdY33FcKnmCKWcOmKuPJqI+zljoHNAL+sXNwOx6l2WQ6ARRd0IP7BvQZmd816GhSHtQHPRxO7SJfqDYNvjlAzG2FIMf4Jx6vvJhXBcabjsN5BCXir4klzSqPaB/Uo8BPNhVV16IAUCG3OxBUTxIIEc1vTKV9C/9EMljKzJG4CrKejST8QIHVvQgAwXt8hUnlBmPsNs+4BN7OhNlLfIrgsPs=
    on_success: change
    on_failure: always
